### ISSUE TITLE
[bulk upload] consistency in the returns of mineral or minerals 

### ISSUE THREAD

**Issue by yongabyte** [metpetdb/api_v2#15]
When user upload a working file, they get an array of "minerals", otherwise it's an array of "mineral"
If it's not too trouble, I hope someone could fix it.
working sample:
![image](https://user-images.githubusercontent.com/11052440/28281903-96f3132c-6af6-11e7-8f86-f43bd25b4051.png)

failed upload sample (bad format): 
![image](https://user-images.githubusercontent.com/11052440/28282019-f5042528-6af6-11e7-8fa8-3d018144bc8d.png)

**Comment by bdrumheller** [comment]
After discussion, this is a non-issue. This behavior is expected.
