### ISSUE TITLE
Emails can't be sent by API

### ISSUE THREAD

**Issue by t3dotgg** [metpetdb/api_v2#3]
From @bdrumheller :

"Authentication is done using Djoser https://github.com/sunscrapers/djoser. Included in this are settings for sending emails for password recovery. I would start by reading into the documentation there. The settings are included in the  a file named `api.env` in the `metpetdb_api` directory. The last time we looked at this, our suspicion was that the environment variables in this file were either not being read or configured correctly."

**Comment by bdrumheller** [comment]
Fixed in https://github.com/metpetdb/api_v2/pull/11
